### ISSUE TITLE
Components are duplicated in the selection dialog

### ISSUE THREAD

**Issue by Antonytm** [exdst/jss-astro-public#13]
**Steps to reproduce:**
1. Open Experience Editor
2. Try to add new component to the page

**Actual result**:
Component are duplicated in the list
![image](https://github.com/exdst/jss-astro-public/assets/647813/c0490eb5-7cea-44cd-8fe9-20f046f5630e)

**Expected result:**
Dialog should show each component only once.

**Comment by Antonytm** [comment]
https://jodosc.blog/2023/06/09/sitecore-10-3-experience-editor-shows-duplicated-rendering-options/

**Comment by bdruziuk** [comment]
> https://jodosc.blog/2023/06/09/sitecore-10-3-experience-editor-shows-duplicated-rendering-options/

In current case described fix is not actual because pipeline is not the part of config.
![image](https://github.com/user-attachments/assets/42d7373d-3875-42e8-8028-ee5f7a776c3b)
But the problem still exists because of order of processors:
Sitecore.ExperienceEditor.Pipelines.GetPlaceholderRenderings.GetAllowedRenderings, Sitecore.ExperienceEditor processor should be the last in the list of <getPlaceholderRenderings> piplines like this:
![image](https://github.com/user-attachments/assets/ab9db3a0-d958-43d0-9cac-9e7dd136bc72)
